apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: otel-demo-local
  namespace: argocd

spec:
  project: default

  sources:
    - repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
      chart: opentelemetry-demo
      targetRevision: 0.38.4
      helm:
        valueFiles:
          - $values/applications/otel-demo/values.yaml

    - repoURL: https://github.com/lackito/otel-demo-gitops-local.git
      targetRevision: main
      ref: values

    - repoURL: https://github.com/lackito/otel-demo-gitops-local.git
      targetRevision: main
      path: applications/otel-demo/manifests

  destination:
    server: https://kubernetes.default.svc
    namespace: opentelemetry-demo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
